# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f5c3a8debd5f366985b539109622546d8c57ddeabd2811607c5c1fcb90ae0f09ae93755b4e33ce8365eab47a485d1f169457e2b6d96f3294d16f4cfb43fe86d

test:
  secret_key_base: cfd0cd84e65d4bcf14e0652f3b6780e2095fd83b90ffde05e76ef57e0ab518201e1437db58ab28c34376dcdc34d65479efd3ad6cade81cddb20399be5b4c3588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
