# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fb20ee321a72167041a964b7d02a8257fabde341bb8564ad663460bb4ec9f6f44b04a7103d2923d3767386a590aec9ca50c18502a2b30be4ec2a4357b2b4eba

test:
  secret_key_base: 40c1cd2469081be09c8cd4c1bf209d90daba330e573cee1ae3c8420a1a939a66ed7fc70d504d96b40420aff1b81fd53eda0bf81be071b72a34de50173f23edbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
