# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d2b901689aa1b44fc8f45194a1ad61162c0023c97a37575629494541aba2017ec84ccb4130d5d15ded213467a63df04efea486791d7b4709d81db73c82d9e61

test:
  secret_key_base: 871c97b2840231ea7c062c5a26f0195f2cda8e3f369b2ac48b1caeff7b0e319c2a8a86904024ff384b7b52508bfd9297f64c199704324d80a2381c13215a2ead

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
