# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd8a671e87abadf95eab8a63fc2077f9e39f3971d3a9bd2df55d9ce9b97b99cb4ca29a4cc6f8c82bcb71a659c933d5d8de3dc76b5bbdb6b21adc8fa63b91a769

test:
  secret_key_base: afeab977e33d72b81c90cebd6918722406fffebf9a89cd7e2ea6b32de8fb08e98dff27ff0721f2d2e6faf9310a8ec36caf2cbabeba325410cdf34d9aa210415f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
