# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99d4890d59d9e91c206f81cdd90ff48fd00ac1bc06377a2e989e1adfd88a53b6de12319fabf1cc3c4f671452e7244797d0d8f04c725b68bba0b9df7086345e52

test:
  secret_key_base: 9f4ffaa210f34946729d898a609da69f52bd352614d84728b02bf6e69f371acb5bd9991d1c6650cbd78b748a1355a991a21d560593757af10123aa923d357a73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
